version: '3'
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  app:
    image: "varann/varann:sha-dfb3fc0"
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432

    restart: on-failure
    depends_on:
      - database