version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - 5432:5432
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

  app:
    image: "varann/varann:sha-51b1429"
    ports:
      - 8080:8080
    env:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: database

    restart: on-failure
    depends_on:
      - database