version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - 5432:5432

  app:
    image: "varann/varann:sha-51b1429"
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432

    restart: on-failure
    depends_on:
      - database