name: Varann workflow
on: [push]
jobs:
  build:
    name: Building
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        -
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0

      - name: Build with Gradle
        run: gradle build

      - name: Build docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: varann/varann
          tag_with_sha: true