name: Varann workflow
on: [push]
jobs:
  build:
    name: Building

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1

      - name: Build with Gradle
        run: gradle build